### ISSUE TITLE
Question regarding RUN->CLEAR circuitry

### ISSUE THREAD

**Issue by hanshuebner** [tebl/RC1802-Cosmac-ELF#4]
Hey,

I am building your computer, thank you for publishing it!  While working on it, I found this in the schematics of the I/O board:

![image](https://user-images.githubusercontent.com/108751/95236908-d1a55a00-0807-11eb-8c5d-00aa41855e8a.png)

I wonder if this is a mistake or whether something is going on which is beyond my limited knowledge of electronics and CMOS buffers.  It looks as if the input of the buffer is directly connected to the output, so what can the buffer do here?

Thanks again! Hans

**Comment by dmadole** [comment]
It is used to debounce the switch. Basically the buffer will hold whatever signal is forced onto it. By shorting the input to VCC or Ground you can override what state it's in already e.g. it's it's high you can force it to low by grounding the input. Yes, this grounds the output also but the CMOS outputs are current limited and it's harmless to do so, especially for the tens of microseconds until the gate changes level.

**Comment by hanshuebner** [comment]
Thank you for the explanation!
